services:
  db:
    image: mysql:8.0
    container_name: guest-book-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: guest-book
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  ai-server:
    image: dddododo/emotion1
    container_name: guest-book-ai
    ports:
      - "8000:8000"
  server:
    image: maruhan/guest-book:latest
    container_name: guest-book-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - ai-server
    restart: always
volumes:
  mysql_data: